import type { ChestConfig, ChestType } from '@/types/game'

export const chestConfigs: Record<ChestType, ChestConfig> = {
  cash: {
    id: 'cash',
    label: '小现金箱',
    rewardCoins: 12,
    penaltyInsurance: 5,
    baseSpeed: 7,
    balloonCount: 2,
    valueRank: 1,
    accent: 'from-emerald-300 to-lime-400',
  },
  standard: {
    id: 'standard',
    label: '普通宝箱',
    rewardCoins: 20,
    penaltyInsurance: 8,
    baseSpeed: 8,
    balloonCount: 3,
    valueRank: 2,
    accent: 'from-orange-300 to-amber-500',
  },
  vault: {
    id: 'vault',
    label: '富人保险箱',
    rewardCoins: 34,
    penaltyInsurance: 14,
    baseSpeed: 8.8,
    balloonCount: 4,
    valueRank: 3,
    accent: 'from-fuchsia-300 to-pink-500',
  },
  gold: {
    id: 'gold',
    label: '黄金宝箱',
    rewardCoins: 52,
    penaltyInsurance: 22,
    baseSpeed: 9.5,
    balloonCount: 5,
    valueRank: 4,
    accent: 'from-yellow-300 to-orange-400',
  },
  ufo: {
    id: 'ufo',
    label: 'UFO 大奖',
    rewardCoins: 88,
    penaltyInsurance: 36,
    baseSpeed: 10,
    balloonCount: 6,
    valueRank: 5,
    accent: 'from-cyan-300 to-purple-500',
    isBoss: true,
  },
}
